name: GradedCategories
version: "2022.03-01"
license: "GPL-2.0-or-later"
date: 2022-03-29
description: |
    Graded closures of categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2022.03-06"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "InfiniteLists"
      version: ">= 2017.08.01"
      url: "https://github.com/homalg-project/InfiniteLists"
    - name: "GroupRepresentationsForCAP"
      version: ">=2017.01.11"
      url: "https://homalg-project.github.io/pkg/GroupRepresentationsForCAP"

suggested-pkgs:
    - name: "IO_ForHomalg"
      version: ">= 2019.01.01"
      url: "https://homalg-project.github.io/pkg/IO_ForHomalg"

www: https://homalg-project.github.io/pkg/GradedCategories
readme: README.md
packageinfo: https://homalg-project.github.io/GradedCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/GradedCategories/releases/download/v2022.03-01/GradedCategories-2022.03-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/GradedCategories/releases/download/v2022.03-01/GradedCategories-2022.03-01.zip

pdf: https://github.com/homalg-project/GradedCategories/releases/download/v2022.03-01/GradedCategories-2022.03-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Graded categories.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZ22</span>]   <b class='BibAuthor'>Barakat, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>GradedCategories, Graded closures of categories,
             Version 2022.03-01</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/GradedCategories">https://homalg-project.github.io/pkg/GradedCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ GradedCategories2022.03-01,
      author =           {Barakat, M. and Zickgraf, F.},
      title =            {{GradedCategories},  Graded  closures  of  categories,
                          {V}ersion 2022.03-01},
      month =            {Mar},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/GradedCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{GradedCategories}}},
      keywords =         {Graded categories},
      printedkey =       {BZ22}
    }

