name: GradedCategories
version: "2020.08.28"
license: "GPL-2.0-or-later"
date: 2020-08-28
description: |
    Graded closures of categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2019.10.29"
      url: "http://homalg-project.github.io/CAP_project/CAP/"
    - name: "InfiniteLists"
      version: ">= 2017.08.01"
      url: "https://github.com/homalg-project/InfiniteLists"
    - name: "GroupRepresentationsForCAP"
      version: ">=2017.01.11"
      url: "http://homalg-project.github.io/CAP_project/"

suggested-pkgs:
    - name: "IO_ForHomalg"
      version: ">= 2019.01.01"
      url: "https://homalg-project.github.io/homalg_project/IO_ForHomalg/"

www: https://homalg-project.github.io/GradedCategories
readme: README.md
packageinfo: https://homalg-project.github.io/GradedCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/GradedCategories/releases/download/v2020.08.28/GradedCategories-2020.08.28.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Graded categories.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZ20</span>]   <b class='BibAuthor'>Barakat, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>GradedCategories, Graded closures of categories,
             Version 2020.08.28</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/GradedCategories">https://homalg-project.github.io/GradedCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ GradedCategories2020.08.28,
      author =           {Barakat, M. and Zickgraf, F.},
      title =            {{GradedCategories}, Graded closures of categories, {V}ersion 2020.08.28},
      month =            {Aug},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/GradedCategories} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{GradedCategories}}},
      keywords =         {Graded categories},
      printedkey =       {BZ20}
    }

